apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
 name: httpbin
 namespace: httpbin
spec:
  selector:
    matchLabels:
      app: httpbin
  jwtRules:
  - forwardOriginalToken: true
    issuer: yoyo@yoyo.com
    jwks: |
      {"keys": [{"n": "uE2_QRlGmkz7EzvCjHeyd0FghVCYEjzwANwe4pPiIvJXq3xJXKtfz3RMUgs20_Hhc4sjY1riJ04GfmryUWNCIww8OPR3D-FCw9tZZSIFplJt5WjYLAH7a4kff2BNlvDlKE-BTTRF6PSENCcmuSx5-ZWjPih0_IU7jiO5XAMGEQaEJjKr8Z7qpUvt0jBwQjJIHLZ1f5WlTtqd-IXLd1eLoRFFc6CgZOI-_XlR_acoUPqsLJNhSyWNYolXOiLmdiMMF0Uu9qz6xSik9Owb427X67GdbJSyMxAhXZ01YlDMnX444Tjf-L53-NwrSqKh44poF8PNgmkz8c6WPXrRaiWrRQ", "e": "AQAB", "kty": "RSA"}]}