apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: keycloak-auth
  namespace: default
spec:
  selector:
    matchLabels:
      app: new-site
  jwtRules:
    - issuer: "http://192.168.39.239:31552/realms/new_site_realm"
      jwksUri: "http://192.168.39.239:31552/realms/new_site_realm/protocol/openid-connect/certs"

