apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default
  #namespace: istio-system # Change that if you want onmly into a specific namespace
  namespace: httpbin
spec:
  mtls:
    mode: STRICT
